parameters:
    hadonra_address.geolocalisation.service.class: Hadonra\Bundle\AddressBundle\Service\GeolocalisationService
    hadonra_address.bazinga_geocoder.provider:
    hadonra_address.address.service.class: Hadonra\Bundle\AddressBundle\Service\AddressService
    hadonra_address.loggable.geocoder.class: Bazinga\Bundle\GeocoderBundle\Geocoder\LoggableGeocoder

services:
    hadonra_address.geolocalisation.service:
        class: %hadonra_address.geolocalisation.service.class%
        arguments:
            - "@hadonra_address.loggable.geocoder"

    hadonra_address.address.service:
        class: %hadonra_address.address.service.class%
        arguments:
            - "@hadonra_address.geolocalisation.service"

    hadonra_address.loggable.geocoder:
        class: %hadonra_address.loggable.geocoder.class%
