language: php

php: [5.4, 5.5]

before_script:
  - curl http://getcomposer.org/installer | php
  - php composer.phar install --dev

notifications:
    email: raldo@chea.io

script : bin/phpunit Tests
